package gui;

import pojazd.PojazdKosmiczny;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class PrzegladGUI<T> {
    public JPanel panel1;
    private JPanel panel2;
    private JComboBox wybierzPojazdComboBox;
    private JCheckBox pojazdWymagaNaprawyCheckBox;
    private JCheckBox naprawaUdanaCheckBox;
    private JButton zatwierdźPrzeglądButton;
    private JButton anulujButton;
    private JComboBox staraCzescComboBox;
    private JComboBox nowaCzescComboBox;
    private JTextField opisNaprawyTextField;
    private JTextField opisPrzegladuTextField;
    private JLabel rozpocznijNaprawęPojazduLabel;
    private JLabel wybierzPojazdLabel;
    private JLabel opisNaprawyLabel;
    private JLabel wybierzNowąCzęśćLabel;
    private JLabel wybierzStarąCzęśćLabel;
    private JLabel opisPrzegladuLabel;

    public PrzegladGUI(Iterable<T> listaPojazdow) {
        for (T pojazd : listaPojazdow) {
            wybierzPojazdComboBox.addItem(pojazd.toString());
        }

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setBackground(new Color(-12828863));
        panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel2.setEnabled(true);
        panel1.add(panel2, BorderLayout.CENTER);
        panel2.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel2.add(panel3, BorderLayout.CENTER);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(panel4, gbc);
        opisPrzegladuLabel = new JLabel();
        opisPrzegladuLabel.setText("Opis przeglądu:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        panel4.add(opisPrzegladuLabel, gbc);
        opisPrzegladuTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(opisPrzegladuTextField, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(panel5, gbc);
        pojazdWymagaNaprawyCheckBox = new JCheckBox();
        pojazdWymagaNaprawyCheckBox.setText("Pojazd wymaga naprawy");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panel5.add(pojazdWymagaNaprawyCheckBox, gbc);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(panel6, gbc);
        wybierzStarąCzęśćLabel = new JLabel();
        wybierzStarąCzęśćLabel.setText("Wybierz starą część:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        panel6.add(wybierzStarąCzęśćLabel, gbc);
        staraCzescComboBox = new JComboBox();
        staraCzescComboBox.setEditable(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(staraCzescComboBox, gbc);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(panel7, gbc);
        wybierzNowąCzęśćLabel = new JLabel();
        wybierzNowąCzęśćLabel.setText("Wybierz nową część:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        panel7.add(wybierzNowąCzęśćLabel, gbc);
        nowaCzescComboBox = new JComboBox();
        nowaCzescComboBox.setEditable(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel7.add(nowaCzescComboBox, gbc);
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(panel8, gbc);
        opisNaprawyLabel = new JLabel();
        opisNaprawyLabel.setText("Opis naprawy:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        panel8.add(opisNaprawyLabel, gbc);
        opisNaprawyTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel8.add(opisNaprawyTextField, gbc);
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(panel9, gbc);
        naprawaUdanaCheckBox = new JCheckBox();
        naprawaUdanaCheckBox.setHideActionText(false);
        naprawaUdanaCheckBox.setText("Naprawa udana");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panel9.add(naprawaUdanaCheckBox, gbc);
        final JPanel panel10 = new JPanel();
        panel10.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(panel10, gbc);
        anulujButton = new JButton();
        anulujButton.setText("Anuluj");
        panel10.add(anulujButton);
        zatwierdźPrzeglądButton = new JButton();
        zatwierdźPrzeglądButton.setText("Zatwierdź przegląd");
        panel10.add(zatwierdźPrzeglądButton);
        final JPanel panel11 = new JPanel();
        panel11.setLayout(new GridBagLayout());
        panel2.add(panel11, BorderLayout.NORTH);
        rozpocznijNaprawęPojazduLabel = new JLabel();
        Font rozpocznijNaprawęPojazduLabelFont = this.$$$getFont$$$(null, -1, 20, rozpocznijNaprawęPojazduLabel.getFont());
        if (rozpocznijNaprawęPojazduLabelFont != null)
            rozpocznijNaprawęPojazduLabel.setFont(rozpocznijNaprawęPojazduLabelFont);
        rozpocznijNaprawęPojazduLabel.setText("Rozpocznij naprawę pojazdu");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panel11.add(rozpocznijNaprawęPojazduLabel, gbc);
        wybierzPojazdLabel = new JLabel();
        wybierzPojazdLabel.setText("Wybierz pojazd:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        panel11.add(wybierzPojazdLabel, gbc);
        wybierzPojazdComboBox = new JComboBox();
        wybierzPojazdComboBox.setEditable(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel11.add(wybierzPojazdComboBox, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}